[package]
name = "house"
version = "0.1.0"
edition = "2021"

[features]
default = ["bevy_asset"]

bevy_asset = ["bevy_internal/bevy_asset"]

[dependencies]
bevy = { version = "0.10.0", features = ["jpeg"] }
bevy_internal = "0.10.0"
rand = "0.8.5"
